### PR TITLE
Fixed issue #5

### PR DESCRIPTION
**Pull request by twoneis**
Fixing #5 by changing all Map<String, String> to Map<String, dynamic>

### CODE REVIEW

**Comment by bramvbilsen** [comment]
In the tutorial, we only use `String` keys and values, thus I do not see how this is relevant for this codebase.

**Comment by twoneis** [comment]
The thing is it doesn't work like this anymore. Same as #3. Please accept both.

**Comment by bramvbilsen** [comment]
Aha, that's new then...

**Review by bramvbilsen — COMMENTED** [review]
All good

**Comment by bramvbilsen** [comment]
It seems like you deleted the pull request @FN2187fo. Can you make a new one?

**Comment by twoneis** [comment]
Here you go #7. I also had to remove the specific version from path_provider, so I can run it with newest Dart SDK.

**Pull request closed without merging**
